import {loadConfig,validateConfig,PROFILE_KEY,PROGRESS_KEY} from './core.js';
const $=s=>document.querySelector(s);let config=await loadConfig();let tracks=[...config.playlists];
const status=message=>$('#settings-status').textContent=message;
function videoId(value){try{const u=new URL(value);let id=u.hostname==='youtu.be'?u.pathname.slice(1):['youtube.com','www.youtube.com','m.youtube.com'].includes(u.hostname)?u.searchParams.get('v')||u.pathname.split('/').pop():'';return /^[\w-]{11}$/.test(id)?id:null;}catch{return null;}}
function renderTracks(){const list=$('#settings-songs');list.replaceChildren();tracks.forEach((song,i)=>{const row=document.createElement('div');row.className='track-row';const name=document.createElement('div');name.textContent=song.title+' · '+song.artist;const b=document.createElement('button');b.type='button';b.className='text-button';b.textContent='Remover';b.onclick=()=>{tracks.splice(i,1);renderTracks();};row.append(name,b);list.append(row);});}
function fill(c){config=c;tracks=[...c.playlists];$('#recipient').value=c.recipient;$('#signature').value=c.signature;$('#start-date').value=c.startDate.slice(0,10);$('#letter').value=c.letter.join('\n\n');$('#favorite-color').value=c.favoriteColor;$('#profession').value=c.profession;$('#hometown').value=c.hometown;$('#anime-order').value=c.animeOrder.join('\n');$('#endpoint').value=c.drive.endpoint;$('#proposal-song').value=c.proposalSong?.type==='youtube'?'https://youtu.be/'+c.proposalSong.videoId:'';$('#extra-config').value=JSON.stringify({science:c.science,photos:c.photos},null,2);$('#current-origin').textContent=location.origin;renderTracks();}
fill(config);
function collect(){const extra=JSON.parse($('#extra-config').value);const proposal=$('#proposal-song').value.trim(),id=proposal?videoId(proposal):null;if(proposal&&!id)throw new Error('Confira o link da música da porta.');return validateConfig({...config,recipient:$('#recipient').value.trim(),signature:$('#signature').value.trim(),startDate:$('#start-date').value+'T00:00:00-03:00',letter:$('#letter').value.trim().split(/\n\s*\n/),favoriteColor:$('#favorite-color').value.trim(),profession:$('#profession').value.trim(),hometown:$('#hometown').value.trim(),animeOrder:$('#anime-order').value.split('\n').map(x=>x.trim()).filter(Boolean),science:extra.science,photos:extra.photos,playlists:tracks,proposalSong:id?{...(config.proposalSong||{}),title:config.proposalSong?.title||'A nossa porta se abre',artist:config.proposalSong?.artist||'A música do nosso momento',type:'youtube',videoId:id}:undefined,drive:{...config.drive,endpoint:$('#endpoint').value.trim()}});}
$('#settings-form').onsubmit=e=>{e.preventDefault();try{config=collect();localStorage.setItem(PROFILE_KEY,JSON.stringify(config));status('Salvo neste aparelho. Baixe o config.json para atualizar a versão que ela vai ver.');}catch(err){status(err.message);}};
$('#download-config').onclick=()=>{try{const c=collect();const blob=new Blob([JSON.stringify(c,null,2)+'\n'],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='config.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Arquivo preparado. Substitua config.json no repositório FORMYLOVE.');}catch(e){status(e.message);}};
$('#import-config').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>1000000)throw new Error('Arquivo muito grande.');fill(validateConfig(JSON.parse(await f.text())));status('Configuração importada. Clique em salvar para aplicar neste aparelho.');}catch(err){status(err.message);}};
$('#restore-defaults').onclick=async()=>{localStorage.removeItem(PROFILE_KEY);fill(validateConfig(await (await fetch('config.json',{cache:'no-cache'})).json()));status('A versão do GitHub está sendo usada neste aparelho.');};
$('#reset-progress').onclick=()=>{localStorage.removeItem(PROGRESS_KEY);status('Os desafios vão começar de novo neste aparelho.');};
$('#add-song').onclick=()=>{const id=videoId($('#song-url').value);if(!id){status('Cole um link válido do YouTube.');return;}if(!$('#song-title').value.trim()){status('Escreva o nome da música.');return;}tracks.push({title:$('#song-title').value.trim(),artist:$('#song-artist').value.trim()||'Uma música nossa',type:'youtube',videoId:id});renderTracks();['song-url','song-title','song-artist'].forEach(k=>$('#'+k).value='');status('Música adicionada à lista. Salve para aplicar.');};
