import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import crypto from 'node:crypto';
function setup(){
  const folderId='albumfolder000000001',files=new Map(),properties=new Map([['ALBUM_FOLDER_ID','albumfolder000000001'],['ALBUM_PASSWORD','test passphrase only'],['ALLOWED_ORIGINS','https://delta-1.github.io']]),cache=new Map();let creations=0;
  const iterator=a=>({hasNext:()=>a.length>0,next:()=>a.shift(),getContinuationToken:()=>''});
  const blob=(bytes,mime='image/jpeg',name='test')=>({getBytes:()=>Array.from(bytes),getContentType:()=>mime,getDataAsString:()=>Buffer.from(bytes).toString(),name});
  function file(id,parent,bytes=Buffer.from([255,216,255,1,2,3,4,5,6,7,8,9])){let desc='';return {getId:()=>id,getName:()=>id,getMimeType:()=> 'image/jpeg',getParents:()=>iterator([{getId:()=>parent}]),isTrashed:()=>false,getThumbnail:()=>null,getSize:()=>bytes.length,getBlob:()=>blob(bytes),getDescription:()=>desc,setDescription:v=>desc=v,getDateCreated:()=>new Date('2026-10-01')};}
  const folder={getName:()=> 'Our album',getFiles:()=>iterator([...files.values()].filter(f=>f.getParents().next().getId()===folderId)),getFilesByName:name=>iterator([...files.values()].filter(f=>f.getName()===name)),createFile:b=>{creations++;const f=file('photo000000000'+creations,folderId,Buffer.from(b.getBytes()));f.getName=()=>b.name;files.set(f.getId(),f);return f;}};
  const context={console,Date,JSON,Math,PropertiesService:{getScriptProperties:()=>({getProperty:k=>properties.get(k),setProperties:p=>Object.entries(p).forEach(([k,v])=>properties.set(k,v)),deleteProperty:k=>properties.delete(k)})},CacheService:{getScriptCache:()=>({get:k=>cache.get(k),put:(k,v)=>cache.set(k,v),remove:k=>cache.delete(k)})},LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})},DriveApp:{getFolderById:id=>{assert.equal(id,folderId);return folder;},getFileById:id=>files.get(id)},Utilities:{getUuid:()=>crypto.randomUUID(),DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(_,s)=>[...crypto.createHash('sha256').update(s).digest()],computeHmacSha256Signature:(s,k)=>[...crypto.createHmac('sha256',k).update(s).digest()],base64EncodeWebSafe:v=>Buffer.from(v).toString('base64url'),base64Encode:v=>Buffer.from(v).toString('base64'),base64Decode:v=>[...Buffer.from(v,'base64')],base64DecodeWebSafe:v=>[...Buffer.from(v,'base64url')],newBlob:(v,m,n)=>blob(typeof v==='string'?Buffer.from(v):v,m,n),formatDate:()=> '2026-10-01'}};
  vm.createContext(context);vm.runInContext(fs.readFileSync(new URL('../drive/Code.gs',import.meta.url),'utf8'),context);context.setupAlbum_();
  const call=(action,payload)=>context.albumRpc({action,payload});const token=call('login',{password:'test passphrase only'}).token;
  return {call,token,files,file,properties,creations:()=>creations};
}
test('password removed after setup and unauthenticated or forged sessions cannot list photos',()=>{const s=setup();assert.equal(s.properties.has('ALBUM_PASSWORD'),false);assert.throws(()=>s.call('list',{}),/acessar/);assert.throws(()=>s.call('list',{token:s.token+'x'}),/Sessão/);assert.throws(()=>s.call('login',{password:'wrong'}),/palavra/);});
test('an authenticated visitor cannot read a Drive photo outside the album',()=>{const s=setup();s.files.set('outside000000001',s.file('outside000000001','another-folder'));assert.throws(()=>s.call('image',{token:s.token,id:'outside000000001'}),/fora/);});
test('upload stores its feeling and deduplicates retries',()=>{const s=setup(),data={token:s.token,requestId:crypto.randomUUID(),data:Buffer.from([255,216,255,0,0,0,0,0,0,0,0,0]).toString('base64'),mime:'image/jpeg',category:'nos',feeling:'Feliz de estar aqui ♡',date:'2026-10-01'};
  const r=s.call('upload',data);assert.equal(r.photo.feeling,data.feeling);assert.equal(s.call('upload',data).duplicate,true);assert.equal(s.creations(),1);assert.equal(s.call('list',{token:s.token}).photos.length,1);
});
test('malformed image bytes and forged iterator tokens are rejected',()=>{const s=setup();assert.throws(()=>s.call('upload',{token:s.token,requestId:crypto.randomUUID(),data:Buffer.from('not a jpeg file').toString('base64'),mime:'image/jpeg',category:'nos',feeling:'',date:'2026-10-01'}),/conteúdo/);assert.throws(()=>s.call('list',{token:s.token,cursor:'forged.signature'}),/Página/);assert.equal(s.creations(),0);});
